spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://******
    username: ******
    password: ******
    type: com.alibaba.druid.pool.DruidDataSource

  banner:
    location: classpath:banner.txt
    charset: UTF-8

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  redis:
    host: 47.98.126.97
    port: 6379
    database: 0
    password: hrq123123
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

mybatis:
  type-aliases-package: edu.hdu.variant1.bean
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    edu.hdu.variant1.mapper: debug
